version: '3.8'

services:
  node-mvc-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=!Mysql123
      - MYSQL_DATABASE=node_mvc_db
      - MYSQL_USER=node_mvc_dba
      - MYSQL_PASSWORD=Password123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
